### ISSUE TITLE
System.ArgumentException: Downloading beatmaps in list file

### ISSUE THREAD

**Issue by Hay1tsme** [naseweis520/osu-Sync#15]
When I try to download any maps, osu!sync crashes. Here's my error log (the song that caused the crash was xi - .357 magnum by Akali)

=====   osu!Sync Crash | 2015-09-11 18:52:30   =====

// Information
An exception occured in osu!Sync. If this problem persists please report it using the Feedback-window, on GitHub or on the osu!Forum.
When reporting please try to describe as detailed as possible what you've done and how the applicationen reacted.
GitHub: http://j.mp/1PDuDFp   |   osu!Forum: http://j.mp/1PDuCkK

// Configuration
{"application":{"isElevated":"True","lastUpdateCheck":"11-09-2015 06:50:43","version":"1.0.0.2"},"config":{"downloadMirror":"0","updateInterval":"3"},"language":{"code":{"long":"en_US","short":"en"}},"system":{"cultureInfo":"en-US","is64bit":"True","operatingSystem":"6.1.7601.65536"}}

// Exception
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at osu_Sync.MainWindow.Importer_Downloader_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by muekoeff** [comment]
**2. Report**
[osu!Forum](https://osu.ppy.sh/forum/p/4500464)
**3. Report**
[osu!Forum](https://osu.ppy.sh/forum/p/4521886)
**4. Report**
[osu!Forum](https://osu.ppy.sh/forum/p/4538686)

**Comment by Hay1tsme** [comment]
Bus still exists in the latest update. This time, however, it starts the download, andf when the loading bar is completely filled, it crashes with this error

```
=====   osu!Sync Crash | 2015-09-30 15:44:00   =====

// Information
An exception occured in osu!Sync. If this problem persists please report it using the Feedback-window, on GitHub or on the osu!Forum.
When reporting please try to describe as detailed as possible what you've done and how the applicationen reacted.
GitHub: http://j.mp/1PDuDFp   |   osu!Forum: http://j.mp/1PDuCkK

// Configuration
{"application":{"isElevated":"True","lastUpdateCheck":"30-09-2015 03:39:04","version":"1.0.0.3"},"config":{"downloadMirror":"0","updateInterval":"3"},"language":{"code":{"long":"en_US","short":"en"}},"system":{"cultureInfo":"en-US","is64bit":"True","operatingSystem":"6.1.7601.65536"}}

// Exception
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at osu_Sync.MainWindow.Importer_Downloader_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by muekoeff** [comment]
I think that the bug is now fixed. The new version 1.0.0.4 will be released in a few minutes or an hour.
