### ISSUE TITLE
System.IO.FileNotFoundException when updating to 1.0.0.4

### ISSUE THREAD

**Issue by Hay1tsme** [naseweis520/osu-Sync#19]
I get this when trying to update, telling me that it can't find the temp file for the update. I can still do it manually though.

```
=====   osu!Sync Crash | 2015-10-15 14:09:19   =====

// Information
An exception occured in osu!Sync. If this problem persists please report it using the Feedback-window, on GitHub or on the osu!Forum.
When reporting please try to describe as detailed as possible what you've done and how the applicationen reacted.
GitHub: http://j.mp/1PDuDFp   |   osu!Forum: http://j.mp/1PDuCkK

// Configuration
{"application":{"isElevated":"True","lastUpdateCheck":"15-10-2015 02:08:09","version":"1.0.0.3"},"config":{"downloadMirror":"0","updateInterval":"3"},"language":{"code":{"long":"en_US","short":"en"}},"system":{"cultureInfo":"en-US","is64bit":"True","operatingSystem":"6.2.9200.0"}}

// Exception
System.IO.FileNotFoundException: Could not find file 'C:\Users\Kevin\AppData\Local\Temp\naseweis520\osu!Sync\Update\osu!Sync Version 1.0.0.4.zip.tmp'.
File name: 'C:\Users\Kevin\AppData\Local\Temp\naseweis520\osu!Sync\Update\osu!Sync Version 1.0.0.4.zip.tmp'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at osu_Sync.Window_Updater.Client_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by muekoeff** [comment]
Should be fixed with 17e3a71 too.
