### ISSUE TITLE
System.ArgumentException: Process '6496' was not found.

### ISSUE THREAD

**Issue by muekoeff** [naseweis520/osu-Sync#26]
[Reported by KriszDev](https://osu.ppy.sh/forum/p/4802183)

``` Indent
=====   osu!Sync Crash | 2016-01-09 11:48:45   =====

// Information
An exception occured in osu!Sync. If this problem persists please report it using the Feedback-window, on GitHub or on the osu!Forum.
When reporting please try to describe as detailed as possible what you've done and how the applicationen reacted.
GitHub: http://j.mp/1PDuDFp   |   osu!Forum: http://j.mp/1PDuCkK

// Configuration
{"application":{"isElevated":"True","lastUpdateCheck":"01-01-2000 00:00:00","version":"1.0.0.8"},"config":{"downloadMirror":"0","updateInterval":"3"},"language":{"code":{"long":"","short":"en"}},"system":{"cultureInfo":"hu-HU","is64bit":"True","operatingSystem":"6.3.9600.0"}}

// Exception
System.ArgumentException: Process '6496' was not found.
   at Microsoft.VisualBasic.Interaction.AppActivate(Int32 ProcessId)
   at osu_Sync.Application.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<_ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by muekoeff** [comment]
Fixed with eb64d0862aa9d266e37494246eb44cfe90d3c6d2
