### ISSUE TITLE
System.NotSupportedException

### ISSUE THREAD

**Issue by muekoeff** [naseweis520/osu-Sync#28]
[Reported by PastLife](https://osu.ppy.sh/forum/p/4819940)

``` Indent
===== osu!Sync Crash | 2016-01-16 16:43:28 =====

// Information
An exception occured in osu!Sync. If this problem persists please report it using the Feedback-window, on GitHub or on the osu!Forum.
When reporting please try to describe as detailed as possible what you've done and how the applicationen reacted.
GitHub: http://j.mp/1PDuDFp | osu!Forum: http://j.mp/1PDuCkK

// Configuration
{"application":{"isElevated":"True","lastUpdateCheck":"16-01-2016 04:43:25","version":"1.0.0.9"},"config":{"downloadMirror":"0","updateInterval":"3"},"language":{"code":{"long":"en_US","short":"en"}},"system":{"cultureInfo":"en-AU","is64bit":"True","operatingSystem":"6.1.7601.65536"}}

// Exception
System.NotSupportedException: No imaging component suitable to complete this operation was found. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x88982F50
--- End of inner exception stack trace ---
at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource)
at osu_Sync.MainWindow.Action_UpdateBeatmapDisplay(List`1 BeatmapList, UpdateBeatmapDisplayDestinations Destination, String LastUpdateTime)
at osu_Sync.MainWindow.BGW__Action_Sync_GetIDs_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by muekoeff** [comment]
Tested and fixed.
