### ISSUE TITLE
System.IO.IOException: App crashes while syncing

### ISSUE THREAD

**Issue by llaver** [naseweis520/osu-Sync#30]
Whether I'm running as admin or not. Tried completely deleting files and appdata, downloading again, and running but it does the same thing. The weird part is it worked once, then I tried to export something and now when I try to sync again it crashes.

```
=====   osu!Sync Crash | 2016-04-08 16:28:57   =====

// Information
An exception occured in osu!Sync. If this problem persists please report it using the Feedback-window, on GitHub or on the osu!Forum.
When reporting please try to describe as detailed as possible what you've done and how the applicationen reacted.
GitHub: http://j.mp/1PDuDFp   |   osu!Forum: http://j.mp/1PDuCkK

// Configuration
{"application":{"isElevated":"False","lastUpdateCheck":"08-04-2016 04:26:34","version":"1.0.0.11"},"config":{"downloadMirror":"0","updateInterval":"3"},"language":{"code":{"long":"en_US","short":"en"}},"system":{"cultureInfo":"en-US","is64bit":"True","operatingSystem":"6.3.9600.0"}}

// Exception
System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.IO.IOException: Invalid string tag
   at osu_Sync.OsuReader.ReadString()
   at osu_Sync.MainWindow.BGW__Action_Sync_GetIDs_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at osu_Sync.MainWindow.BGW__Action_Sync_GetIDs_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by muekoeff** [comment]
Hello llaver,
the problem occured while syncing - i.e. reading the osu!.db file.
I tried to recreate your issue and at first failed. However, after starting osu! and restarting it because of its update I ran into the problem too. After having a look at the [release notes (b20160409.3)](https://osu.ppy.sh/p/changelog?v=b20160409.3&s=stable40&l=b20160403.4) I came to the conclusion that this issue is because of an update of the format how osu! stores its cached data.
I will try to find I solution though I don't know how long it will take.

**Comment by muekoeff** [comment]
**Reason.** Incompatible osu!.db due to [changes](http://is.gd/eVTDaI)
**Solution.** _n/a_
**Solution (Dev).** {
:: Update to new [file format](https://osu.ppy.sh/wiki/Db_%28file_format%29)
:: (Re-)Enable old "Folder-Detection-Sync" as fallback }
