### ISSUE TITLE
Can't sync for the first time

### ISSUE THREAD

**Issue by Hay1tsme** [naseweis520/osu-Sync#4]
Setting the osu! path and clicking "Get Beatmap Sets" causes this error and a crash:
"System.NullReferenceException: Object reference not set to an instance of an object.
   at osu_Sync.MainWindow.BGW__Action_Sync_GetIDs_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)"

**Comment by muekoeff** [comment]
I've just published version 0.0.0.8 of osu!Sync.
I'm not quite sure if this bug is fixed there but it might be due to some code optimisations.

**Comment by Hay1tsme** [comment]
I can sync now, so whatever you did worked! :3

**Comment by muekoeff** [comment]
That's great.  Ｏ(≧∇≦)Ｏ
